#!/usr/bin/env bash

OPTION="${1}"

if [ ! -z "${ROOTPATH}" ]; then
	echo ":: We have changed the semantic and doesn't need the ROOTPATH"
	echo ":: variable anymore"
fi

generate_synapse_file() {
	local filepath="${1}"

	 SYNAPSE_SERVER_NAME="${SERVER_NAME}" SYNAPSE_REPORT_STATS="${REPORT_STATS}" /start.py generate
}

# ${SERVER_NAME}.log.config is autogenerated via --generate-config
configure_log_config() {
	sed -i "s|.*filename:\s/homeserver.log|        filename: /data/homeserver.log|g" "/data/${SERVER_NAME}.log.config"
}

case $OPTION in
    	"start")
		echo "-=> start matrix"
        	exec /start.py 
		;;

	"autostart")
		if [ -f /data/homeserver.yaml ]; then
            
                   echo "-=> start matrix"
                   exec /start.py 
               else
            breakup="0"
            [[ -z "${SERVER_NAME}" ]] && echo "STOP! environment variable SERVER_NAME must be set" && breakup="1"
            [[ -z "${REPORT_STATS}" ]] && echo "STOP! environment variable REPORT_STATS must be set to 'no' or 'yes'" && breakup="1"
            [[ "${REPORT_STATS}" != "yes" ]] && [[ "${REPORT_STATS}" != "no" ]] && \
                echo "STOP! REPORT_STATS needs to be 'no' or 'yes'" && breakup="1"

            [[ "${breakup}" == "1" ]] && exit 1

            echo "-=> generate synapse config"
            generate_synapse_file /data/homeserver.tmp

            /home_server_config.py

	    echo "-=> configure some settings in ${SERVER_NAME}.log.config"
            configure_log_config

            echo ""
            echo "-=> you have to review the generated configuration file homeserver.yaml"
        fi
        ;;

	"stop")
		echo "-=> stop matrix"
		echo "-=> via docker stop ..."
		;;

	"version")
		echo "-=> Matrix Version"
		cat /synapse.version
		;;

	"diff")
		echo "-=> Diff between local configfile and a fresh generated config file"
		echo "-=>      some values are different in technical point of view, like"
		echo "-=>      autogenerated secret keys etc..."

		DIFFPARAMS="${DIFFPARAMS:-Naur}"
		SERVER_NAME="${SERVER_NAME:-demo_server_name}"
		REPORT_STATS="${REPORT_STATS:-no_or_yes}"
		export SERVER_NAME REPORT_STATS

		generate_synapse_file /tmp/homeserver.synapse.yaml
		/home_server_config.py /tmp/homeserver.synapse.yaml
		
		diff -${DIFFPARAMS} /tmp/homeserver.synapse.yaml /data/homeserver.yaml
		;;

	"generate")
		breakup="0"
		[[ -z "${SERVER_NAME}" ]] && echo "STOP! environment variable SERVER_NAME must be set" && breakup="1"
		[[ -z "${REPORT_STATS}" ]] && echo "STOP! environment variable REPORT_STATS must be set to 'no' or 'yes'" && breakup="1"
		[[ "${REPORT_STATS}" != "yes" ]] && [[ "${REPORT_STATS}" != "no" ]] && \
			echo "STOP! REPORT_STATS needs to be 'no' or 'yes'" && breakup="1"

		[[ "${breakup}" == "1" ]] && exit 1

		echo "-=> generate synapse config"
		generate_synapse_file /data/homeserver.tmp
		echo "-=> configure some settings in homeserver.yaml"
		configure_homeserver_yaml $turnkey /data/homeserver.tmp

		mv /data/homeserver.tmp /data/homeserver.yaml
                /home_server_config.py

		echo "-=> configure some settings in ${SERVER_NAME}.log.config"
		configure_log_config

		echo ""
		echo "-=> you have to review the generated configuration file homeserver.yaml"
		;;

	*)
		echo "-=> unknown \'$OPTION\'"
		exec "$@"
		;;
esac

